### ISSUE TITLE
Question about training multiple frames and fusion mechanism

### ISSUE THREAD

**Issue by zef1611** [lucas-ventura/CoVR#11]
Hi, thank you for your great work.

I have run the code and noticed that the given code only provides for single-frame training and missing the fusion mechanism (MLP, CA). It would be wonderful if you could provide the full version of those functions.

Thank you for this wonderful work.

**Comment by lucas-ventura** [comment]
Hi, thanks so much for your interest in our work!

- **Fusion Mechanism**: The CA (cross-attention) fusion mechanism is actually the default throughout the experiments discussed in the paper and within the repository. 

- **MLP Experiment**: You can find the configuration for the MLP experiment in the [``covr_late-fusion.yaml``](https://github.com/lucas-ventura/CoVR/blob/master/configs/experiment/covr_late-fusion.yaml) file. To run it, use the following command: ``python train.py experiment=covr_late-fusion``.

- **Single Frame and Multi-Frame Configurations**: This repository primarily focusses on single-frame queries targeting multiple frames, as outlined in our main paper. The multi-frame query scenario, mentioned in Table A.4 of the Appendix, involves a significant increase in computational overhead. In order to keep the number of target frames constant using the same batch size, we had to pre-extract frame embeddings from the input video and store them in memory. It is necessary to save not just the CLS token but all tokens, each frame's embedding is of size [577, 1024] - IIRC. As you might expect, this can lead to memory requirements in the order of hundreds of GBs. If you're planning to replicate this setup or have further questions, feel free to ask :)

I hope this helps clarify your questions. Feel free to reach out if you need further information.
