### ISSUE TITLE
The inquiry about test CIRR dataset

### ISSUE THREAD

**Issue by gersys** [lucas-ventura/CoVR#19]
Hi, thank you for this wonderful work.

I appreciate you providing the code.

I wonder how to calculate the recall performance of CIRR

I ran the code, but I think the code saves the image list of top-50 similarities, doesn't calculate the recall performance

So I checked the annotations of CIRR test-1, However, there is no label of the target image, only 'members'.

How do I calculate the recall performance of CIRR?

It would be beneficial to me

**Comment by lucas-ventura** [comment]
Hi,

There are no labels for the CIRR test set because they are not public. When you run `python test.py test=cirr` (or `train.py` with `test=cirr`), it will generate a `recalls_cirr.json` in the output folder. You will need to upload this to [https://cirr.cecs.anu.edu.au/test_process/](https://cirr.cecs.anu.edu.au/test_process/) to get the test results.

Let me know if you have any further questions.

Best regards,
Lucas

**Comment by gersys** [comment]
Thank you for fast and kind reply :)
